name: Schedule Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Before
        run: |
          pwd
          ls -ltr
          hostname
      - name: Checkout
        uses: actions/checkout@v6.1.0
      - name: After
        run: |
          pwd >> artifact.txt
          ls -ltr
          hostname
      - name: Upload file
        uses: actions/upload-artifact@v7.0.1
        with:
          name: single_file
          path: ./artifact.txt