name: my-first-workflow
# To get a trigger on every push in this
on: push

jobs:
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    steps:
      - name: Running Single Command in Job1
        run: echo "Hello"
      - name: OS Release
        run: cat /etc/os-release
      - name: Calling sleep
        run: sleep 20
  
  job2:
    name: JOB2
    runs-on: ubuntu-latest
    steps:
      - name: Runner Hostname
        run: hostname
      - name: Multiple Commands
        run: |
          echo "Hello everyone"
          echo "My name is Periklis `date`"
          sleep 20