name: Schedule Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Before
        run: |
          pwd
          ls -ltr
          hostname
      - name: Checkout
        uses: actions/checkout@v7.0.1
      - name: After
        run: |
          pwd >> artifact.txt
          mkdir artifacts
          echo `ls -ltr` >> artifacts/list.txt
          echo `hostname` >> artifacts/hostname.txt
      - name: Upload file
        uses: actions/upload-artifact@v7.0.1
        with:
          name: single_file
          path: ./artifact.txt
      - name: Upload from directory
        uses: actions/upload-artifact@v7.0.1
        with:
          name: directory_artifacts_path
          path: artifacts/
      - name: Upload from multiple paths
        uses: actions/upload-artifact@v7.0.1
        with:
          name: multiple_paths
          path: |
            ./artifact.txt
            artifacts/